---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exo-webtest
spec:
  template:
    spec:
      containers:
      - name: exo-webtest
        image: exo.container-registry.com/exoscale-images/exo-webtest:dev