apiVersion: v1
kind: Service
metadata:
  labels:
    app: exo-webtest
  name: exo-webtest
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: exo-webtest
  type: LoadBalancer
